apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: development
  labels:
    app: kong
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
        env: development
    spec:
      containers:
        - name: kong
          image: kong:3.8
          ports:
            - name: proxy
              containerPort: 8000
            - name: admin
              containerPort: 8001
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/etc/kong/kong.yml"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"
          volumeMounts:
            - name: kong-config-vol
              mountPath: /etc/kong/kong.yml
              subPath: kong.yml
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /status
              port: 8001
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 6
      volumes:
        - name: kong-config-vol
          configMap:
            name: kong-config
