apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    env: development
    app: nesnes
---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    env: staging
    app: nesnes
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    env: production
    app: nesnes
