apiVersion: v1
kind: Secret
metadata:
  name: nesnes-secret
  namespace: staging
  labels:
    app: nesnes
    env: staging
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASS: "stg-postgres-secure-pass-2024"
  JWT_SECRET: "staging-jwt-secret-nesnes-key-2024-change-this"
  PGADMIN_EMAIL: "admin@admin.com"
  PGADMIN_PASS: "stg-admin-pass-2024"
