apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
  labels:
    app: nesnes-frontend
    env: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nesnes-frontend
  template:
    metadata:
      labels:
        app: nesnes-frontend
        env: production
    spec:
      containers:
        - name: nesnes-frontend
          image: agnesabexheti/nesnes-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
